# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
defaults: &defaults
  docker:
    - image: circleci/node:8.11
  working_directory: ~/repo
jobs:
  prepare:
    <<: *defaults
    steps:
      - run:
          name: Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter

  lint:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - dev-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dev-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: dev-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Linting tests
          command: |
            npm run lint && node scripts/utils/checkWipCommits

  coverage:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/tmp
      # Download and cache dependencies
      - restore_cache:
          keys:
            - dev-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dev-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: dev-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Coverage tests
          command: |
            npm run test:coverage
            ./tmp/cc-test-reporter format-coverage -t lcov -o tmp/codeclimate.json coverage/lcov.info
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.json

  upload-coverage:
    <<: *defaults
    environment:
      - CC_TEST_REPORTER_ID: df3abd3219266522d7d6e0a50c9a6258a7e96b76be38eaf886fac185a8a48356
    steps:
      - attach_workspace:
          at: ~/repo/tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.json

  deployment:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Installing deployment dependencies
          command: |
            sudo apt-get update
            sudo apt-get install python -y
            sudo apt-get install python-pip -y
            pip install awscli --upgrade
            pip install awsebcli --upgrade
            pip install docker-compose --upgrade
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/jm_api.tar
      - run:
          name: Load Docker image layer cache
          command: |
            docker load -i /caches/jm_api.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=jm_api -t jm_api .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/jm_api.tar jm_api
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/jm_api.tar
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              login="$(aws ecr get-login)"
              ${login}
              docker tag jm_api "${ECR_ENDPOINT}/jm_api:${CIRCLE_SHA1}"
              docker push "${ECR_ENDPOINT}/jm_api:${CIRCLE_SHA1}"
            fi

workflows:
  version: 2
  commit:
    jobs:
      - lint
      - prepare
      - coverage:
          requires:
            - lint
            - prepare
      - upload-coverage:
          requires:
            - lint
            - prepare
            - coverage
      - deployment:
          requires:
            - lint
            - prepare
            - coverage
            - upload-coverage
          filters:
            branches:
              only:
                - staging
                - master
